### ISSUE TITLE
Can this plugin use postgresql?

### ISSUE THREAD

**Issue by TafkaMax** [maubot/supportportal#1]
Hi

We are using the maubot infrastructure and after installing this plugin we noticed it created its own sqlite db, eventhough we have a db set for our maubot instance.

Can this plugin use the maubot db we have created?

**Comment by williamkray** [comment]
the comments in the [maubot sample config](https://github.com/maubot/maubot/blob/master/maubot/example-config.yaml#L31-L37) say:

    # The connection URL for plugin databases. If null, all plugins will get SQLite databases.
    # If set, plugins using the new asyncpg interface will get a Postgres connection instead.
    # Plugins using the legacy SQLAlchemy interface will always get a SQLite connection.

and this plugin has lots of sqlalchemy things in the code, so i'm guessing the answer is `no`.

**Comment by TafkaMax** [comment]
Ah thanks. I missed that point. Seems to be so.
